version: "4.19"

services:
  burenie:
    image: bogdars/burenie:work
    container_name: burenie
    volumes:
      - static_volume:/bur_form/static
    env_file:
      - .env
    command: >
      sh -c "gunicorn -b 0.0.0.0:8000 bur_form.wsgi:application"

  nginx:
    build: 
      dockerfile: ./Dockerfile
      context: ./nginx/
    container_name: burenie_nginx
    image: burenie_nginx
    volumes:
      - static_volume://bur_form/static
    depends_on:
      - burenie
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume: