version: "4.19"

services:
  burenie:
    image: bogdars/burenie:work
    container_name: burenie
    volumes:
      - static_volume://form_page/static
    command: sh -c "python3 manage.py collectstatic --no-input &&
                    python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    gunicorn bur_form.wsgi -b 0.0.0.0:8000"
    env_file:
      - .env
    expose:
      - 8000
    ports:
      - 8000:8000
    restart: "on-failure"

  nginx:
    build: 
      dockerfile: ./Dockerfile
      context: ./nginx/
    container_name: burenie_nginx
    image: burenie_nginx
    volumes:
      - static_volume://form_page/static
    depends_on:
      - burenie
    expose:
     - 80
    ports:
      - "80:80"

volumes:
  static_volume: